export const STOPS_LIST = [
    'Fu\u00dfweg nach Borthen',
    'Sobrigauer Weg',
    'Lugaer Platz',
    'Kelterei',
    'Luga',
    'Krebser Stra\u00dfe',
    'Am Galgenberg',
    'Lockwitz',
    'H\u00e4nichenweg',
    'Krebser Stra\u00dfe Nord',
    'Altlockwitz',
    'Hp Zschachwitz',
    'Theilestra\u00dfe',
    'Helena-Rott-Stra\u00dfe',
    'Arno-Schellenberg-Stra\u00dfe',
    'Urnenstra\u00dfe',
    'Alter Postweg',
    'Nickerner Weg',
    'Veilchenstra\u00dfe',
    'Tronitzer Stra\u00dfe',
    'Fritz-Schreiter-Stra\u00dfe',
    'S\u00f6brigen',
    'Bedrich-Smetana-Stra\u00dfe',
    'Borsbergblick',
    'Erich-K\u00e4stner-Stra\u00dfe',
    'Niedersedlitzer Platz',
    'H\u00fcfnerweg',
    'Struppener Stra\u00dfe',
    'Altnickern',
    'Dorfstra\u00dfe',
    'Kurt-Tucholsky-Stra\u00dfe',
    'Johannes-Brahms-Stra\u00dfe',
    'Prof-Billroth-Stra\u00dfe',
    'Freibad Wostra',
    'S\u00f6brigener Stra\u00dfe',
    'G\u00f6ppersdorfer Weg',
    'Am Br\u00fcchigt',
    'Sosaer Stra\u00dfe',
    'M\u00fchlenstra\u00dfe',
    'Prohlis Einkaufszentrum',
    'Windm\u00fchlenstra\u00dfe',
    'Am Wiesenrand',
    'Bf Niedersedlitz',
    'Prohlis Gleisschleife',
    'Am Waldrand',
    'F\u00f6rsterlingstra\u00dfe',
    'Sch\u00f6naer Stra\u00dfe',
    'An der Post',
    'Ernst-Toller-Stra\u00dfe',
    'Fritz-Meinhardt-Stra\u00dfe',
    'Wostra',
    'Georg-Palitzsch-Stra\u00dfe',
    'Bahnhofstra\u00dfe',
    'Dorfplatz Oberpoyritz',
    'Stra\u00dfe des 17. Juni',
    'Zur Elbinsel',
    'Reisstra\u00dfe',
    'Gombsener Stra\u00dfe',
    'Putjatinplatz',
    'Leubnitzer H\u00f6he',
    'Am Sch\u00f6psdamm',
    'Gondelweg',
    'Jacob-Winter-Platz',
    'Guerickestra\u00dfe',
    'Hermann-Michel-Stra\u00dfe',
    'Gamigstra\u00dfe',
    'Wei\u00dfdornstra\u00dfe',
    'Niedersedlitzer Stra\u00dfe',
    'Dampfschiffstra\u00dfe',
    'Koloniestra\u00dfe',
    'Kurhausstra\u00dfe',
    'Lohmener Stra\u00dfe',
    'Stuttgarter Stra\u00dfe',
    'Zschierener Stra\u00dfe',
    'Kastanienstra\u00dfe',
    'Kauschaer Stra\u00dfe',
    'Meu\u00dflitzer Stra\u00dfe',
    'Freystra\u00dfe',
    'Albert-Wolf-Platz',
    'Pillnitzer Platz',
    'Gewerbegebiet Gittersee',
    'Heckenweg',
    'F\u00e4hrstelle Kleinzschachwitz',
    'Tornaer Stra\u00dfe',
    'Heilbronner Stra\u00dfe',
    'Keppgrundstra\u00dfe',
    'Rathausstra\u00dfe',
    'Berthold-Haupt-Stra\u00dfe',
    'Trattendorfer Stra\u00dfe',
    'Niederseidewitzer Weg',
    'Rathaus Leuben',
    'Thomas-Mann-Stra\u00dfe',
    'Betriebshof Reick',
    'M\u00fegelner Stra\u00dfe',
    'F\u00e4hrstelle Pillnitz',
    'Mockethaler Stra\u00dfe',
    'Hp Dobritz',
    'Wilhelm-Liebknecht-Stra\u00dfe',
    'Altleuben',
    'Am Anger',
    'Klosterteichplatz',
    'T\u00fcbinger Stra\u00dfe',
    'Rathaus Pillnitz',
    'Seidnitzer Weg',
    'Bodemerweg',
    'H\u00fcl\u00dfe-Gymnasium',
    'Bannewitzer Stra\u00dfe',
    'Marie-Wittich-Stra\u00dfe',
    'Altreick',
    'Babisnauer Stra\u00dfe',
    'Kleinnaundorfer Stra\u00dfe',
    'Friedhof Leuben',
    'H\u00fcl\u00dfestra\u00dfe',
    'Rottwerndorfer Stra\u00dfe',
    'Breitscheidstra\u00dfe',
    'Karl-Laux-Stra\u00dfe',
    'Pillnitz Leonardo-da-Vinci-Stra\u00dfe',
    'Altkaitz',
    'Campingplatz Mockritz',
    'Gebauerstra\u00dfe',
    'M\u00fcnzteichweg',
    'Eichbergstra\u00dfe',
    'Altmockritz',
    'Neuostra',
    'Van-Gogh-Stra\u00dfe',
    'Spitzwegstra\u00dfe',
    'Vollmarstra\u00dfe',
    'Wilhelm-Busch-Stra\u00dfe',
    'Wilhelm-Busch-Stra\u00dfe Ost',
    'Cosch\u00fctz',
    'Lohrmannstra\u00dfe',
    'Altleubnitz',
    'Robert-Sterl-Stra\u00dfe',
    'Abzweig nach Reick',
    'Kadenstra\u00dfe',
    'Achtbeeteweg',
    'Innsbrucker Stra\u00dfe',
    'Gro\u00dfglocknerstra\u00dfe',
    'Clausen-Dahl-Stra\u00dfe',
    'An der Rennbahn',
    'Wieckestra\u00dfe',
    'Gitterseebr\u00fccke',
    'Cunnersdorfer Stra\u00dfe',
    'Enno-Heidebroek-Stra\u00dfe',
    'Mockritz',
    'Altdobritz',
    'Dorfhainer Stra\u00dfe',
    'Schiffswerft Laubegast',
    'An der Obstplantage',
    'Ludwig-Renn-Allee',
    'Saarstra\u00dfe',
    'M\u00fcnzmeisterstra\u00dfe',
    'Zschertnitzer Stra\u00dfe',
    'Dohnaer Stra\u00dfe',
    'H\u00f6ckendorfer Weg',
    'Otto-Dix-Ring',
    'S\u00fcdh\u00f6he',
    'Lassallestra\u00dfe',
    'Mockritz Otto-Pilz-Stra\u00dfe',
    'Heidenschanze',
    'Corinthstra\u00dfe',
    'Bahnhof Reick',
    'Laibacher Stra\u00dfe',
    'Kotteweg',
    'Leiblstra\u00dfe',
    'Pferderennbahn',
    'C\u00e4mmerswalder Stra\u00dfe',
    'Bergfelderweg',
    'Hugo-B\u00fcrkner-Stra\u00dfe',
    'Felsenkeller',
    'Begerburg',
    'Dora-Stock-Stra\u00dfe',
    'Eugen-Bracht-Stra\u00dfe',
    'Kronst\u00e4dter Platz',
    'Rubensweg',
    'Prof.-Ricker-Stra\u00dfe',
    'Reichenhaller Stra\u00dfe',
    'R\u00e4cknitzh\u00f6he',
    'Paradiesstra\u00dfe',
    'Stadtgutstra\u00dfe',
    'Winterbergstra\u00dfe',
    'Schurichtstra\u00dfe',
    'Mockritzer Stra\u00dfe',
    'Westendstra\u00dfe',
    'Leubener Stra\u00dfe',
    'C\u00e4cilienstra\u00dfe',
    'D\u00f6lzschen',
    'N\u00e4therstra\u00dfe',
    'Gustavheim',
    'Marienberger Stra\u00dfe',
    'Helmholtzstra\u00dfe',
    'Burgenlandstra\u00dfe',
    'Heinrich-Zille-Stra\u00dfe',
    'Regensburger Stra\u00dfe',
    'Caspar-David-Friedrich-Stra\u00dfe',
    'Plauenscher Ring',
    'Troppauer Stra\u00dfe',
    'Rennplatzstra\u00dfe',
    'Mommsenstra\u00dfe',
    'Plauen N\u00f6thnitzer Stra\u00dfe',
    'Liebenauer Stra\u00dfe',
    'Hermann-Seidel-Stra\u00dfe',
    'Betriebshof Gruna',
    'Wasaplatz',
    'Kaitzer Stra\u00dfe',
    'Cosch\u00fctzer Stra\u00dfe',
    'Zellescher Weg',
    'Staffelsteinstra\u00dfe',
    'Rauensteinstra\u00dfe',
    'Gasanstaltstra\u00dfe',
    'Knappestra\u00dfe',
    'Staats- und Universit\u00e4tsbibliothek',
    'Alfred-Thiele-Stra\u00dfe',
    'Rathaus Plauen',
    'Alttolkewitz',
    'Hp Plauen',
    'Tiergartenstra\u00dfe',
    'Technische Universit\u00e4t (Fr.-Foerster-Platz)',
    'M\u00fcnchner Platz',
    'Fraunhofer-Institutszentrum',
    'Liebst\u00e4dter Stra\u00dfe',
    'Einkaufszentrum Seidnitz',
    'Grunaer Weg',
    'Hp Strehlen',
    'Wilischstra\u00dfe',
    'Weberplatz',
    'R\u00fcdesheimer Stra\u00dfe',
    'F\u00e4hrstelle Tolkewitz',
    'N\u00fcrnberger Platz',
    'Fritz-Schulze-Stra\u00dfe',
    'Kipsdorfer Stra\u00dfe',
    'F\u00e4hrstelle Niederpoyritz',
    'Moosleite',
    'Julius-Otto-Stra\u00dfe',
    'D\u00f6lzschener Stra\u00dfe',
    'Hepkestra\u00dfe',
    'Beerenhut',
    'Kasseler Stra\u00dfe',
    'Strehlener Platz',
    'Altfranken',
    'Lengefelder Stra\u00dfe',
    'Bamberger Stra\u00dfe',
    'Wasserwerk Tolkewitz',
    'S\u00fcdvorstadt',
    'Zwinglistra\u00dfe',
    'B\u00e4rensteiner Stra\u00dfe',
    'Neunimptscher Stra\u00dfe',
    'Bernhardstra\u00dfe',
    'Querallee',
    'Altnau\u00dflitz',
    'W\u00fcrzburger Stra\u00dfe',
    'Mohorner Stra\u00dfe',
    'Reichenbachstra\u00dfe',
    'K\u00f6lner Stra\u00dfe',
    'Altenberger Platz',
    'Tolkewitz Urnenhain',
    'Berggie\u00dfh\u00fcbler Stra\u00dfe',
    'Johannisfriedhof',
    'Schneebergstra\u00dfe',
    'Kurzer Schritt',
    'Frankenbergstra\u00dfe',
    'Saalhausener Stra\u00dfe',
    'Reisewitzer-/Frankenbergstr',
    'Chemnitzer Stra\u00dfe',
    'Uhlandstra\u00dfe',
    'Zoo',
    'Schaufu\u00dfstra\u00dfe',
    'Karcherallee',
    'Altwachwitz',
    'Junghansstra\u00dfe',
    'Schl\u00fcterstra\u00dfe',
    'Clara-Zetkin-Stra\u00dfe',
    'Striesen Ludw.-Hartmann-Stra\u00dfe',
    'Clara-Viebig-Stra\u00dfe',
    'Lenn\u00e9platz',
    'Zwickauer Stra\u00dfe',
    'Hauptbahnhof (Friedrich-List-Platz)',
    'Gret-Palucca-Stra\u00dfe',
    'Bonhoefferplatz',
    'Am Altfrankener Park',
    'Altenberger Stra\u00dfe',
    'Lipsiusstra\u00dfe',
    'Agentur f\u00fcr Arbeit',
    'Hepkeplatz',
    'Kapellenweg',
    'Altnossener Stra\u00dfe',
    'Hirtenstra\u00dfe',
    'Hauptbahnhof',
    'W\u00f6lfnitzer Ring',
    'Josef-Herrmann-Stra\u00dfe',
    'Mansfelder Stra\u00dfe',
    'Gottleubaer Stra\u00dfe',
    'Hauptbahnhof Nord',
    'Ebertplatz',
    'Comeniusplatz',
    'Gustav-Freytag-Stra\u00dfe',
    'Schillingstra\u00dfe',
    'Schweizer Stra\u00dfe',
    'Julius-Vahlteich-Stra\u00dfe',
    'Koblenzer Stra\u00dfe',
    'Gro\u00dfer Garten',
    'Malterstra\u00dfe',
    'Pohlandplatz',
    'Hans-Dankner-Stra\u00dfe',
    'W\u00f6lfnitz',
    'Bergmannstra\u00dfe',
    'Neuer Annenfriedhof',
    'B\u00fcnaustra\u00dfe',
    'Niederwaldplatz',
    'Spenerstra\u00dfe',
    'Tharandter Stra\u00dfe',
    'Saxoniastra\u00dfe',
    'Budapester Stra\u00dfe',
    'Walpurgisstra\u00dfe',
    'Ammonstra\u00dfe / Budapester Stra\u00dfe',
    'Merianplatz',
    'Mosenstra\u00dfe',
    'Oederaner Stra\u00dfe',
    'Dornbl\u00fcthstra\u00dfe',
    'L\u00f6btau Gr\u00f6belstra\u00dfe',
    'Amalie-Dietrich-Platz',
    'K\u00fcnstlerhaus',
    'Josephinenstra\u00dfe',
    'Conertplatz',
    'Heinrich-Sch\u00fctz-Stra\u00dfe',
    'Stra\u00dfburger Platz',
    'Kirschenstra\u00dfe',
    'Dahlienweg',
    'Wernerstra\u00dfe',
    'Fetscherplatz',
    'Rosenstra\u00dfe',
    'Reitbahnstra\u00dfe',
    'Krankenhaus Sankt Joseph-Stift',
    'Betriebshof Gorbitz',
    'Wittenberger Stra\u00dfe',
    'Oehmestra\u00dfe',
    'Prager Stra\u00dfe',
    'Niederwaldstra\u00dfe',
    'Deutsches Hygiene-Museum',
    'Webergasse',
    'Coventrystra\u00dfe',
    'Hp Freiberger Stra\u00dfe',
    'Schlehenstra\u00dfe',
    'Burgkstra\u00dfe',
    'Pennricher Stra\u00dfe',
    'Berggartenstra\u00dfe',
    'J\u00fcngststra\u00dfe',
    'Chamissostra\u00dfe',
    'H\u00fcblerplatz',
    'Striesener Stra\u00dfe',
    'Pirnaischer Platz',
    'Gabelsbergerstra\u00dfe',
    'St.-Benno-Gymnasium',
    'Weidentalstra\u00dfe',
    'Jacobistra\u00dfe',
    'Altmarkt',
    'Cottaer Stra\u00dfe',
    'Rochwitz B\u00fchlauer Stra\u00dfe',
    'Alfred-Althus-Stra\u00dfe',
    'Auf der H\u00f6he',
    'Hutbergstra\u00dfe',
    'Gerichtsstra\u00dfe',
    'Postplatz',
    'W\u00e4gnerstra\u00dfe',
    'Calberlastra\u00dfe',
    'Kretschmerstra\u00dfe',
    'Semmelweisstra\u00dfe',
    'Hebbelplatz',
    'Kotzschweg',
    'D\u00fcrerstra\u00dfe',
    'Schillerplatz',
    'Arthur-Weineck-Stra\u00dfe',
    'Trinitatisplatz',
    'Adalbert-Stifter-Weg',
    'Synagoge',
    'Grillparzerstra\u00dfe',
    'Schweriner Stra\u00dfe',
    'Blasewitzer Stra\u00dfe / Fetscherstra\u00dfe',
    'Gorbitzer Stra\u00dfe',
    'Gerokstra\u00dfe',
    'Prellerstra\u00dfe',
    'Altomsewitz',
    'Birkenhainer Stra\u00dfe',
    'Amselsteg',
    'Omsewitz',
    'Permoserstra\u00dfe',
    'Augsburger Stra\u00dfe',
    'Theaterplatz',
    'Hornweg',
    'G\u00fcntzplatz',
    'Altburgst\u00e4dtel',
    'Lene-Glatzer-Stra\u00dfe',
    'Malerstra\u00dfe',
    'K\u00f6nigsheimplatz',
    'Lise-Meitner-Stra\u00dfe',
    'Obere Station Schwebebahn',
    'K\u00f6rnerplatz',
    'Sachsenallee',
    'Am Zwingerteich',
    'Sch\u00e4ferstra\u00dfe',
    'Zweibr\u00fcderweg',
    'B\u00f6nischplatz',
    'Bahnhof Mitte',
    'Tatzberg',
    'Bahnhof Friedrichstadt',
    'Quohrener Stra\u00dfe',
    'Pfeifferhannsstra\u00dfe',
    'Ri\u00dfweg',
    'Universit\u00e4tsklinikum',
    'Manitiusstra\u00dfe',
    'Altcotta',
    'Maxstra\u00dfe (Bf Mitte)',
    'Scharfensteinstra\u00dfe',
    'Gutenbergstra\u00dfe',
    'Carolaplatz',
    'Neust\u00e4dter Markt',
    'Waltherstra\u00dfe',
    'Freiheit',
    'Wei\u00dferitzstra\u00dfe',
    'Obere Station Standseilbahn',
    'Kongresszentrum / Haus der Presse',
    'Steglichstra\u00dfe',
    'Am Steinigt',
    'Neubertstra\u00dfe',
    'Elisabethstra\u00dfe',
    'Kongresszentrum  (Devrientstr.)',
    'Pfotenhauerstra\u00dfe',
    'Ockerwitzer Stra\u00dfe',
    'Martin-Opitz-Stra\u00dfe',
    'Johannstadt',
    'Hamburger Stra\u00dfe',
    'T\u00e4nnichtstra\u00dfe',
    'Rosa-Luxemburg-Platz',
    'Leutewitz',
    'Krankenhaus Friedrichstadt (Sportpark Ostra)',
    'Cunewalder Stra\u00dfe',
    'Palaisplatz',
    'K\u00e4the-Kollwitz-Ufer',
    'Betriebshof Waltherstra\u00dfe',
    'Rossendorfer Stra\u00dfe',
    'Bremer Stra\u00dfe',
    'Vorwerkstra\u00dfe',
    'Gottfried-Keller-Stra\u00dfe',
    'Taubenberg',
    'Fl\u00fcgelweg',
    'F\u00e4hrstelle Johannstadt',
    'Cossebauder Stra\u00dfe (Haltepunkt Cotta)',
    'Grundstra\u00dfe',
    'Am Wei\u00dfen Adler',
    'Hegereiterstra\u00dfe',
    'Droste-H\u00fclshoff-Stra\u00dfe',
    'Hp Cotta',
    'Neub\u00fchlauer Stra\u00dfe',
    'B\u00fchlau Ullersdorfer Platz',
    'F\u00e4hrstelle Neustadt',
    'Bautzner Stra\u00dfe / Rothenburger Stra\u00dfe',
    'Anton-/Leipziger Stra\u00dfe',
    'Alberthafen',
    'Pulsnitzer Stra\u00dfe',
    'Albertplatz',
    'Plattleite',
    'Schunckstra\u00dfe',
    'Am Lehmberg',
    'Diakonissenkrankenhaus',
    'Mordgrundbr\u00fccke',
    'Bf. Neustadt (Eisenbahnstr.)',
    'Bahnhof Neustadt',
    'Elbschl\u00f6sser',
    'G\u00f6rlitzer Stra\u00dfe',
    'Nordstra\u00dfe',
    'Bahnhof Neustadt (Hansastra\u00dfe)',
    'Hermann-L\u00f6ns-Stra\u00dfe',
    'Angelikastra\u00dfe',
    'Merbitzer Stra\u00dfe',
    'Wilhelminenstra\u00dfe',
    'Waldschl\u00f6\u00dfchen',
    'Schulberg',
    'Mobschatzer H\u00f6he',
    'Alter Schlachthof',
    'Hammeraue',
    'Louisenstra\u00dfe',
    'Messering (Halle 1)',
    'Am Zschonergrundbad',
    'Dammweg',
    'B\u00f6hmertstra\u00dfe',
    'Schleswiger Stra\u00dfe',
    'Werftstra\u00dfe',
    'F\u00e4hrstelle Ostragehege',
    'L\u00f6\u00dfnitzstra\u00dfe',
    'Mengsstra\u00dfe',
    'Waldschl\u00f6\u00dfchenstra\u00dfe',
    'Messe Dresden',
    'Alaunplatz',
    'F\u00e4hrstelle Eisenberger Stra\u00dfe',
    'J\u00e4gerpark Heideblick',
    'Alexander-Puschkin-Platz',
    'Landesdirektion Sachsen',
    'Arno-Holz-Allee',
    'Th\u00e4terstra\u00dfe',
    'Bischofsweg',
    'Zschonergrundstra\u00dfe',
    'Bischofsplatz',
    'Messe Gleisschleife',
    'Schneise 8',
    'Mathias-Oeder-Stra\u00dfe',
    'Hp Kemnitz',
    'Kaditzer Stra\u00dfe',
    'Gro\u00dfenhainer Platz',
    'Marienallee',
    'Friedensstra\u00dfe',
    'Overbeckstra\u00dfe',
    'Fischhausstra\u00dfe',
    '\u00dcbigau',
    'Tannenstra\u00dfe',
    'Scharfenberger Stra\u00dfe',
    'Rethelstra\u00dfe',
    'Oschatzer Stra\u00dfe',
    'Gro\u00dfenhainer Stra\u00dfe / Fritz-Reuter-Stra\u00dfe',
    'Flensburger Stra\u00dfe',
    'Hans-Oster-Stra\u00dfe',
    'Liststra\u00dfe',
    'Stauffenbergallee',
    'B\u00fcrgerstra\u00dfe',
    'Liststra\u00dfe (Harkortstra\u00dfe)',
    'An der Flutrinne',
    'Rathaus Pieschen',
    'Altpieschen',
    'Rudolf-Leonhard-Stra\u00dfe',
    'Schanzenstra\u00dfe',
    'Gewerbegebiet Kaditz',
    'Buchenstra\u00dfe',
    'Pestalozziplatz',
    'Trachauer Stra\u00dfe',
    'Podemusstra\u00dfe',
    'S\u00f6rnewitzer Stra\u00dfe',
    'Mickten',
    'Hp Stetzsch',
    'Wurzener Stra\u00dfe',
    'Hp Pieschen',
    'B\u00e4rwalder Stra\u00dfe',
    'Eschebachstra\u00dfe',
    'Heeresb\u00e4ckerei',
    'ElbePark',
    'Zeithainer Stra\u00dfe',
    'Bunsenstra\u00dfe',
    'W\u00e4chterstra\u00dfe',
    'Washingtonstra\u00dfe',
    'Am Urnenfeld',
    'Riegelplatz',
    'Oberauer Stra\u00dfe',
    'Alttrachau',
    'Altkaditz',
    'Trachenberger Platz',
    'Gohlis',
    'F\u00fcrstenhainer Stra\u00dfe',
    'Rankestra\u00dfe',
    'Industriegel\u00e4nde',
    'Markusfriedhof',
    'Sankt-Pauli-Friedhof',
    'Betriebshof Trachenberge',
    'Boxdorfer Stra\u00dfe',
    'Rankestra\u00dfe / Peschelstra\u00dfe',
    'Seewiesenweg',
    'Wilder-Mann-Stra\u00dfe',
    'R\u00fcckertstra\u00dfe',
    'Am Trachauer Bahnhof',
    'Schillerstra\u00dfe',
    'Obergohlis',
    'Maxim-Gorki-Stra\u00dfe',
    'Fehrmannweg',
    'Gartenstra\u00dfe',
    'Dungerstra\u00dfe',
    'Justizvollzugsanstalt',
    'Hp Trachau',
    'Hubertusplatz',
    'Krankenhaus Neustadt',
    'Geblerstra\u00dfe',
    'Fabricestra\u00dfe',
    'Kolpingstra\u00dfe',
    'Kopernikusstra\u00dfe',
    'Spitzhausstra\u00dfe',
    'Lauterbacher Stra\u00dfe',
    'Kleestra\u00dfe',
    'Windm\u00fchlenweg',
    'Niedergohlis S\u00fcdstr',
    'Dorothea-Erxleben-Stra\u00dfe',
    'Kaditz Am Vorwerksfeld',
    'Hellersiedlung',
    'Stephanstra\u00dfe',
    'Am Hellerhof',
    'Niedergohlis Dorfstra\u00dfe',
    'Platanenstra\u00dfe',
    'Heidem\u00fchle',
    'Aachener Stra\u00dfe',
    'Diebsteig',
    'Wilder Mann',
    'Hellerhofstra\u00dfe',
    'Neul\u00e4nder Stra\u00dfe',
    'Moritzburger Weg',
    'Hellerberge',
    'Infineon S\u00fcd',
    'Heidefriedhof',
    'Klotzsche Infineon',
    'Infineon Nord',
    'Markt Hellerau',
    'Am Olter',
    'Karl-Marx-Stra\u00dfe',
    'Am Hellerrand',
    'Rathaus Klotzsche',
    'Heinrich-Tessenow-Weg',
    'Festspielhaus Hellerau',
    'Gr\u00fcner Weg',
    'Elsterweg',
    'Zur Neuen Br\u00fccke',
    'Stralsunder Stra\u00dfe',
    'Bahnhof Klotzsche',
    'Brunnenweg',
    'An der Jungen Heide',
    'Am Festspielhaus',
    'D\u00f6rnichtweg',
    'Zinnowitzer Stra\u00dfe',
    'Hellerau Kiefernweg',
    'Waldteichstra\u00dfe',
    'L\u00f6\u00dfnitzweg',
    'Am Steinacker',
    'Beckerstra\u00dfe',
    'Karlshagener Weg',
    'Keulenbergstra\u00dfe',
    'Sa\u00dfnitzer Stra\u00dfe',
    'Ahlbecker Stra\u00dfe',
    'K\u00e4the-Kollwitz-Platz',
    'Flughafenstra\u00dfe',
    'Reineckeweg',
    'Selliner Stra\u00dfe',
    'Fontane-Center',
    'Altwilschdorf',
    'Flughafen Terminal 1',
    'Arkonastra\u00dfe',
    'Flughafen West',
    'Sagarder Weg',
    'Putbuser Weg',
    'Flughafen',
    'R\u00e4hnitzer Allee',
    'Klotzsche Maria-Reiche-Stra\u00dfe',
    'Wilschdorfer Landstra\u00dfe',
    'Flugzeugwerke',
    'Grenzstra\u00dfe (Bus)',
    'Wilschdorf Industriegebiet',
    'Industriepark Klotzsche',
    'Bahnhof Grenzstra\u00dfe',
    'Hugo-Junkers-Ring',
    'Ikarusweg',
    'Zur Steinh\u00f6he',
    'Zum Windkanal',
    'Schwimmhalle Klotzsche',
    'Industriegebiet Nord',
];
